<p>&nbsp;</p>
<p><strong>PRIVACY POLICY</strong></p>
<p><strong>Game</strong> : Funny Kids Drawing</p>
<p><strong>Developer</strong>: CyTech</p>
<p><strong>Contact Information of Data Owner:</strong></p>
<p>cy.technology@gmail.com</p>
<p>&nbsp;</p>
<p><strong>About this Privacy Policy</strong></p>
<p>This privacy policy applies to data obtained from you when you use our Funny Kids Drawing mobile applications.</p>
<p>Our Privacy Policy explains what personal and non-personal information we collect from you, how we obtain it, how we secure it, how we share it, how you can access and modify it, and how you can restrict how we share it. The Privacy Policy also explains some of your legal rights regarding your personal data.</p>
<p><strong>Important Terms</strong></p>
<p>- "NON-PERSONAL DATA" is information that is not personally identifiable in any way.</p>
<p>- "PERSONAL DATA" means any information relating to an identified or identifiable natural person ("data owner"); An identifiable natural person is a person who can be identified directly or indirectly by reference to an identifier such as a name, identification number, location data, an online identifier, or one or more factors specific to physical, physiological, genetic, mental characteristics. , the economic, cultural or social identity of the natural person in question. PD is in many ways the same as Personally Identifiable Information (PII). However, the scope of PD is broader and covers more data.</p>
<p>- "GDPR" is the EU General Data Protection Regulation (2016/679).</p>
<p>- "COPPA" is the US Children's Online Privacy Protection Rule.</p>
<p>- "CCPA" is the California Consumer Privacy Act of 2018.</p>
<p><strong>What information is collected and how do we intend to use it?</strong></p>
<p>We may collect personal data from you when you use Funny Kids Drawing. For the sake of public accountability, we explain in detail what personal information we collect and access, why we use it, and the legal basis on which we handle your personal data.</p>
<p>When you use Funny Kids Drawing, we use such data for the following purposes:</p>
<p>- To confirm your age;</p>
<p>- To save your game progress;</p>
<p>- To respond to deck emails.</p>
<p>&nbsp;</p>
<p><strong>Analytical data</strong></p>
<p>When you download Funny Kids Drawing from the Google Play Store, we use Firebase (https://firebase.google.com), a third-party analytics service provided by Google LLC, that collects the following technical personal and non-personal data from you. :</p>
<p>- Number of sessions;</p>
<p>- Session duration;</p>
<p>- Eclipse;</p>
<p>- Events;</p>
<p>- Upload resource;</p>
<p>- IDFA.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>We use such data for the following purposes:</p>
<p>- analyze the technical aspects of your use of our games;</p>
<p>- Optimizing our applications according to your needs;</p>
<p>- prevention of fraud and abuse;</p>
<p>- Provide security;</p>
<p>&nbsp;</p>
<p><strong>Data Types Used</strong></p>
<p>1- Crash logs: The collected data is processed for a short time. It is used to improve application analysis and performance. These data are collected compulsorily.</p>
<p>2- Other data on application performance: The collected data is processed for a short time. It is used to improve application analysis and performance. These data are collected compulsorily.</p>
<p>3- Files and Documents: The collected data is processed for a short time. It is used for the functionality of the application. It is used to save the game operation and then continue from where the user left off. These data are collected compulsorily.</p>
<p>4- Application activity: The collected data is processed for a short time. Used for application functionality and analysis. These data are collected compulsorily.</p>
<p>&nbsp;</p>
<p><strong>Sale of Personal Data</strong></p>
<p>We do not sell your personal data to third parties and have no such plans in the future.</p>
<p>&nbsp;</p>
<p><strong>Use of Your Personal Information</strong></p>
<p>Funny Kids Drawing does not collect personal user data</p>
<p>&nbsp;</p>
<p><strong>Ads</strong></p>
<p>Funny Kids Drawing shows ads. Google Admob service is used for the advertisement service shown. The maximum Ad content rating is set to G (General Audiences). All areas and advertising content that may be objectionable for children are blocked through Google Admob.</p>
<p>&nbsp;</p>
<p><strong>Sharing Information with Affiliates and Other Third Parties</strong></p>
<p>We do not sell or rent your personal information to third parties for marketing purposes. We may share your personal information with third-party service providers (our data processors) working on our behalf. These third-party service providers include:</p>
<p>Our analytics service provider Google Firebase (https://firebase.google.com);</p>
<p>Storage and Disposal of Your Personal Data</p>
<p>We only use information about you (including your personal data) momentarily for analytics and application performance. We do not permanently store your data on a server.</p>
<p>Protecting Children's Privacy</p>
<p>We do not collect personal data from children under the age of consent or who are unable to provide valid consent under COPPA or GDPR.</p>
<p>&nbsp;</p>
<p><strong>Changes to the Privacy Policy</strong></p>
<p>We reserve the right to change our Privacy Policy at any time. We are always aware of what personal data we collect, use and disclose. We will provide updates to the Website and Apps so that you are always up to date.</p>
